// Code generated by ent, DO NOT EDIT.

package bug

import (
	"entedge/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Bug {
	return predicate.Bug(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Bug {
	return predicate.Bug(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Bug {
	return predicate.Bug(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Bug {
	return predicate.Bug(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Bug {
	return predicate.Bug(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Bug {
	return predicate.Bug(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Bug {
	return predicate.Bug(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Bug {
	return predicate.Bug(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Bug {
	return predicate.Bug(sql.FieldLTE(FieldID, id))
}

// BugID applies equality check predicate on the "bug_id" field. It's identical to BugIDEQ.
func BugID(v int) predicate.Bug {
	return predicate.Bug(sql.FieldEQ(FieldBugID, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Bug {
	return predicate.Bug(sql.FieldEQ(FieldDescription, v))
}

// BugIDEQ applies the EQ predicate on the "bug_id" field.
func BugIDEQ(v int) predicate.Bug {
	return predicate.Bug(sql.FieldEQ(FieldBugID, v))
}

// BugIDNEQ applies the NEQ predicate on the "bug_id" field.
func BugIDNEQ(v int) predicate.Bug {
	return predicate.Bug(sql.FieldNEQ(FieldBugID, v))
}

// BugIDIn applies the In predicate on the "bug_id" field.
func BugIDIn(vs ...int) predicate.Bug {
	return predicate.Bug(sql.FieldIn(FieldBugID, vs...))
}

// BugIDNotIn applies the NotIn predicate on the "bug_id" field.
func BugIDNotIn(vs ...int) predicate.Bug {
	return predicate.Bug(sql.FieldNotIn(FieldBugID, vs...))
}

// BugIDGT applies the GT predicate on the "bug_id" field.
func BugIDGT(v int) predicate.Bug {
	return predicate.Bug(sql.FieldGT(FieldBugID, v))
}

// BugIDGTE applies the GTE predicate on the "bug_id" field.
func BugIDGTE(v int) predicate.Bug {
	return predicate.Bug(sql.FieldGTE(FieldBugID, v))
}

// BugIDLT applies the LT predicate on the "bug_id" field.
func BugIDLT(v int) predicate.Bug {
	return predicate.Bug(sql.FieldLT(FieldBugID, v))
}

// BugIDLTE applies the LTE predicate on the "bug_id" field.
func BugIDLTE(v int) predicate.Bug {
	return predicate.Bug(sql.FieldLTE(FieldBugID, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Bug {
	return predicate.Bug(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Bug {
	return predicate.Bug(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Bug {
	return predicate.Bug(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Bug {
	return predicate.Bug(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Bug {
	return predicate.Bug(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Bug {
	return predicate.Bug(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Bug {
	return predicate.Bug(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Bug {
	return predicate.Bug(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Bug {
	return predicate.Bug(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Bug {
	return predicate.Bug(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Bug {
	return predicate.Bug(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Bug {
	return predicate.Bug(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Bug {
	return predicate.Bug(sql.FieldContainsFold(FieldDescription, v))
}

// HasTags applies the HasEdge predicate on the "tags" edge.
func HasTags() predicate.Bug {
	return predicate.Bug(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TagsTable, TagsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTagsWith applies the HasEdge predicate on the "tags" edge with a given conditions (other predicates).
func HasTagsWith(preds ...predicate.Tag) predicate.Bug {
	return predicate.Bug(func(s *sql.Selector) {
		step := newTagsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Bug) predicate.Bug {
	return predicate.Bug(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Bug) predicate.Bug {
	return predicate.Bug(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Bug) predicate.Bug {
	return predicate.Bug(func(s *sql.Selector) {
		p(s.Not())
	})
}
