// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Bug is the predicate function for bug builders.
type Bug func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// Image is the predicate function for image builders.
type Image func(*sql.Selector)

// Pet is the predicate function for pet builders.
type Pet func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
